# Generated by Django 5.2.6 on 2025-09-18 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patienttracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='verified',
            field=models.BooleanField(default=False),
        ),
    ]
