# Generated by Django 5.2.6 on 2025-09-19 05:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patienttracking', '0002_patientdata_verified'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='patientdata',
            name='tracking_type',
            field=models.CharField(choices=[('HEARTBEAT', 'Heartbeat'), ('SUGAR', 'Sugar'), ('COLESTROL', 'Colestrol')], default='HEARTBEAT', max_length=20),
        ),
    ]
