# Generated by Django 5.2.6 on 2025-09-19 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patienttracking', '0003_alter_patientdata_patient_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='tracking_type',
            field=models.CharField(choices=[('HEARTBEAT', 'Heartbeat'), ('SUGAR', 'Sugar'), ('COLESTROL', 'Colestrol')], max_length=20),
        ),
    ]
