# Generated by Django 5.2.6 on 2025-09-19 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patienttracking', '0004_alter_patientdata_tracking_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdata',
            name='unit',
            field=models.CharField(blank=True, choices=[('BPM', 'Beats Per Minute'), ('MG_DL_SUGAR', 'Milligrams per Deciliter (Sugar)'), ('MG_DL_COLESTROL', 'Milligrams per Deciliter (Cholesterol)')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='patientdata',
            name='value',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
