# Generated by Django 5.2.6 on 2025-09-19 10:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patienttracking', '0005_patientdata_unit_patientdata_value'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientdata',
            name='value',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
